### PR TITLE
LL-244: Login Page

### PR DESCRIPTION
**Pull request by Jihnboii**
# Description
Created Two buttons, one for github login and another for google log in. Also a Forgot Password button.

Subsequent # 
LL-244

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] npm run dev
- [X] open page to Login

# Checklist (when relevant):

- [X] My code follows the style guidelines of this project
      [TypeScript](https://google.github.io/styleguide/tsguide.html)
      [Schema](<https://learn.microsoft.com/en-us/previous-versions/windows/desktop/forefront-2010/ee652242(v=vs.100)>)
- [X] I have included a reviewer on the pull request [*Replace this text with the reviewer*]
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by aematei** [comment]
Hey @Jihnboii this is looking great! Here are some things I think you could do to match up more closely with the Figma:

1. Shorten the distance between the two buttons.
2. Bring the "Forgot Password?..." line closer to the google button.
3. Give the icons some more space on the right before the button text begins.
4. Move the features up the page, closer to the header.
5. Make the features a bit bigger.
6. Remove scroll bar from this page

Otherwise, I think that should do it. Some extra things to work on, if you have time:
1. I noticed you're using both`mt` and `mb` on elements. Consider sticking with only one of those, when they overlap (for instance, the google button only really needs `mt` if the GH button doesn't have `mt`. This way, one only needs to adjust one of those to control the spacing.
2. Also, notice how there is considerable overlap between the two buttons' code. If you have time, you can refactor the button code into a single component (either in the same module or another). That way, you can simply instantiate a new button and pass any necessary props (like the icon).
3. Also, maybe talk with @alinz22 about sharing the button component between your pages, since they are very similar.

**Comment by aematei** [comment]
@Jihnboii looking good! I think the sizing is a lot closer to the Figma model. We may actually want to revisit the rest of the frontend code and update the sizing to match this. @pogi7 any thoughts on the sizing?

One thing you'll want to get going on this ticket is the hover highlighting. You can check the Figma presentations out for examples of the light and dark mode login pages.

**Review by pogi7 — CHANGES_REQUESTED** [review]
@Jihnboii Please look at the [Figma prototype](https://www.figma.com/file/jl3d5wO6lGLwKhXvrD4kBl/Design-Implementation?type=design&node-id=0%3A1&mode=design&t=2rvMVDjf9MAlaXgF-1) for the Login page:
Light Page:
image
Dark Page:
image

**Comment by aematei** [comment]
Hey John, looks good! Just make sure you've got the right border thickness and border-radius value on the buttons (the outline), then you should be good to go. One you're done with that, post this PR in the frontend channel and ask for a review so Arron can also take a look. We should be good to merge it then. Great job!

**Comment by aematei** [comment]
image

**Comment by aematei** [comment]
Looks good to me @Jihnboii! Merge pending @pogi7's approval.

**Pull request merged**
