### PR TITLE
LL-224 Add Dark Mode functionality to front page content components

### PR DESCRIPTION
**Pull request by aematei**
# Description

...and fix 'electric-blue' color name. The last merged branch used electric-blue for a color that is not electric-blue, which will cause a collision with proper usage of that color name, down the line.

LL-224

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] 1) npm install
- [x] 2) npm ~~start~~ run dev
- [x] 3) Viewed in browser to ensure components agree with Figma prototype
- [x] 4) add `dark` class to `outer <div> in the the Content component in components/Content.tsx` to test dark mode styles

# Checklist (when relevant):

- [x] My code follows the style guidelines of this project
[TypeScript](https://google.github.io/styleguide/tsguide.html)
[Schema](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/forefront-2010/ee652242(v=vs.100))
- [x] I have included a reviewer on the pull request [@pogi7 @WhenitStarted @alinz22 ]
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by WhenitStarted** [comment]
Dark mode seems to be working when I drop the ``` dark ``` name into the div for the cards on line 22 in the 
_components/Content.tsx_  file. Below is a result output which does match the figma design

darkMode_Feature

**Review by pogi7 — APPROVED** [review]
lgtm!

**Review by WhenitStarted — COMMENTED** [review]
Runs and doesn't give any error or problems on the terminal or page

**Comment by aematei** [comment]
Thanks y'all. Merging.

**Pull request merged**
